apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-config
  namespace: monitoring
data:
  telegraf.conf: |
    [agent]
      interval = "5s"
      round_interval = true

    [[inputs.cpu]]
    [[inputs.mem]]
    [[inputs.net]]
    [[inputs.disk]]

    [[outputs.prometheus_client]]
      listen = ":9273"
